BOFNAME := CredEnum
CC_x64 := x86_64-w64-mingw32-gcc
CC_x86 := i686-w64-mingw32-gcc

all:
	$(CC_x64) -o $(BOFNAME).x64.o $(COMINCLUDE) -c CredEnum.c
	$(CC_x86) -o $(BOFNAME).x86.o $(COMINCLUDE) -c CredEnum.c